apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - namespace.yaml
  - kafka.yaml
  - selection.yaml
  - migration.yaml
  - fitness-sudoku.yaml
  - generator-sudoku.yaml
  - crossover-sudoku.yaml
  - mutation-sudoku.yaml
  - orchestrator.yaml
