apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration
  namespace: ga-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migration
  template:
    metadata:
      labels:
        app: migration
    spec:
      containers:
        - name: migration
          image: umair121/migration:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: NUM_ISLANDS
              value: "4"
            - name: MIGRATION_TOPOLOGY
              value: "ring"
          readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: migration
  namespace: ga-pipeline
spec:
  selector:
    app: migration
  ports:
    - port: 8000
      targetPort: 8000
